update python tests workflow

diff --git a/.github/workflows/python_test_challenge_ci.yaml b/.github/workflows/python_test_challenge_ci.yaml
--- a/.github/workflows/python_test_challenge_ci.yaml
+++ b/.github/workflows/python_test_challenge_ci.yaml
@@ -4,9 +4,11 @@ on:
   push:
     paths:
       - 'python/test_challenge/**'
-  pull_request:
-    paths:
-      - 'python/test_challenge/**'
+  
+defaults:
+  run:
+    shell: bash
+    working-directory: ./python/test_challenge
 
 jobs:
   test:
@@ -18,9 +20,31 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.8'
+          python-version: '3.10'
       
       - name: Run unit tests
         run: |
           cd python/test_challenge
           python -m unittest test_main.py -v
+  
+  points-system:
+    runs-on: ubuntu-latest
+    needs: test
+    defaults:
+      run:
+        shell: bash
+        working-directory: .
+    steps:
+      - name: Check secrets and increment points
+        shell: bash
+        run: |
+          if [[ -n "${{ secrets.GKSS_LEADERBOARD_API_URL }}" && -n "${{ secrets.GKSS_LEADERBOARD_API_KEY }}" ]]; then
+            echo "Incrementing points..."
+            curl -X POST ${{ secrets.GKSS_LEADERBOARD_API_URL }} \
+              -H "x-gkssunisa-api-key: ${{ secrets.GKSS_LEADERBOARD_API_KEY }}" \
+              -H "Content-Type: application/json" \
+              -d '{"message": "i did it! ${{ github.actor }}"}'
+          else
+            echo "Skipping points increment - required secrets not found"
+            exit 1
+          fi
